excerpt_separator: ""
markdown: kramdown
url: http://www.gunvant.net
title: Gunvant kathrotiya
tagline: A log of dev life
description: 
paginate: 5
highlighter: rouge
gems:
  - jekyll-sitemap
  
# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""  
  

theme: jekyll-theme-minimal