excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://www.gunvant.net
title: gunvant
tagline: A log of dev life
description: 
paginate: 5

gems:
  - jekyll-sitemap
  
# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""  
  
